version: '3'

services:
  # Web application
  webapp:
    container_name: webapp
    build: .
    ports:
      - 8000:8080
    environment:
      - FLASK_SECRET_KEY=dev-secret-key
      - GEMINI_API_KEY=${GEMINI_API_KEY:-demo_api_key}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY:-demo_api_key}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT:-https://example.openai.azure.com}
      - AZURE_OPENAI_MODEL_NAME=${AZURE_OPENAI_MODEL_NAME:-gpt-4}
    volumes:
      - ./app:/app/app
      - ./app/uploads:/app/app/uploads